url: https://www.frnlab.com
baseurl: 

# Site settings
title: FRN Lab
email: support@frnlab.com
description: "lightweight system monitoring utility for mac os x. system indicator on mac menu bar"


social:
  - title: twitter
    url: http://twitter.com/frnlab
  - title: facebook
    url:
  - title: bitbucket 
    url: http://bitbucket.org/frnlab

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty
